language: c
sudo: false
addons:
  apt:
    packages:
      - libsqlite3-dev
before_script:
  - ./configure --maintainer --full --allextmod --disable-docs
script:
  - make test
  - ./test-bootstrap-jim
